### ISSUE TITLE
Why dataloader iteration number is strange?

### ISSUE THREAD

**Issue by DevKiHyun** [zyzisyz/mfa_conformer#14]
Hi, thank you to share your official code of mfa_conformer.

I also implement your score successfully, but I have one of question.

When I run your code, the total number of data loader is 10,912.

Actually, the total number of  Vox1&2's utterances is 1,240,651, and batch_size is 200. Then, the estimated iteration numbers should be 6203.

What is 10,912 - 6,203 = 4709 iterations ?

Thanks

**Comment by DevKiHyun** [comment]
I found that it is just for Eval utterances.

**Comment by skxooo** [comment]
> I found that it is just for Eval utterances.

Could the evaluation progress bar (last 4709 interations) refresh at a faster rate? It appears the eval_dataset might be using batch_size=1?
